FROM node:18-alpine

WORKDIR /app/client
COPY client/package*.json .

RUN npm install

COPY client/ .

WORKDIR /app/server
COPY server/package*.json .
COPY server/yarn.lock .

RUN yarn install

COPY server/ .

EXPOSE 8080

CMD ["yarn", "start"]